// GIT E GITHUB

// GIT = LINHAS DE COMANDOS QUE IUSAMOS PARA SALVAR NOSSOS ARQUIVOS (COMO SR FOSSE O CTRL + v CTRL + v)






//GITHUB =  SERIA A PASTA QUE ESSES ARQUIVOS SÃO SALVOS (É COMO SE FOSSE A PASTA)

clear